# app:
#     build: .
#     ports:
#         - "3000:3000"
#     links:
#         - database
#         - rai
#     volumes:
#         - "src:/src"
#     environment:
#     - ROOT_URL=http://localhost
#     - MONGO_URL=mongodb://database:27017/meteor
# database:
#   image: mongo
#   command: mongod --smallfiles --quiet --logpath=/dev/null
# rai:
#     image: clemahieu/rai_node
#     ports:
#         - "7075:7075"
#         - "7075:7075/udp"
#         - "7076:7076"
#     command: /rai_node --daemon


#version: '2'
#
#services:
#  app:
#    build: .
#    ports:
#         - "3000:3000"
#    environment:
#        - ROOT_URL=http://localhost
#        - MONGO_URL=mongodb://database:27017/meteor
#    networks:
#        - back
 # database:
  #  image: mongo
  #  ports:
 #        - "27017:27017"
 #   command: mongod --smallfiles --quiet --logpath=/dev/null
 #   networks:
 #       - back
#
#networks:
#  back:
    # Use a custom driver which takes special options
    #driver: custom-driver-2


version: '2'

services:
  app:
    build: .
    ports:
         - "3000:3000"
    environment:
        - ROOT_URL=https://crypto-folio.herokuapp.com/
        - MONGO_URL=mongodb://database:27017/meteor
    networks:
        - back
  database:
    image: mongo
    ports:
         - "27017:27017"
    command: mongod --smallfiles --quiet --logpath=/dev/null
    networks:
        - back

networks:
  back:
    # Use a custom driver which takes special options
    #driver: custom-driver-2
